CREATE TYPE public.account_type AS ENUM
    ('client', 'employee', 'admin');

ALTER TYPE public.account_type
    OWNER TO furta31640;

CREATE TABLE public.`classification` {
	classification_id INT GENERATED BY DEFAULT AS IDENTITY,
	classification_name CHARACTER VARYING NOT NULL,
	CONSTRAINT classification_pk PRIMARY KEY (classification_id)
}:

CREATE TABLE IF NOT EXISTS public.`inventory` {
    inv_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    inv_make character varying NOT NULL,
    inv_model
    inv_year
    inv_description
    inv_image
    inv_thumbnail
    inv_price
    inv_miles
    inv_color
    classification_id
    CONSTRAINT inventory_pkey PRIMARY KEY (inv_id)
};

ALTER TABLE IF EXISTS public.inventory
    ADD CONSTRAINT fk_classification FOREIGN KEY (classification_id)
    REFERENCES public.classification (classification_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE NO ACTION;

CREATE TABLE IF NOT EXISTS public.account
(
    account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_firstname character varying NOT NULL,
    account_lastname character varying NOT NULL,
    account_email character varying NOT NULL,
    account_password character varying NOT NULL,
    account_type account_type NOT NULL DEFAULT 'Client'::account_type,
    CONSTRAINT account_pkey PRIMARY KEY (account_id)
);